// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSRKDy4mAekmREUGlfZwEBAXqh23BQyY',
    appId: '1:566798140808:web:478dec23288412df05663d',
    messagingSenderId: '566798140808',
    projectId: 'vaulted-f1ef6',
    authDomain: 'vaulted-f1ef6.firebaseapp.com',
    storageBucket: 'vaulted-f1ef6.firebasestorage.app',
    measurementId: 'G-8RRLKVQL9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5fhY3zCSnjztwTjJIg8NClWC4j-YJMA',
    appId: '1:566798140808:android:0923050387bdb4d405663d',
    messagingSenderId: '566798140808',
    projectId: 'vaulted-f1ef6',
    storageBucket: 'vaulted-f1ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZy64V38COUJj537xS-yiof-zv-R_27VQ',
    appId: '1:566798140808:ios:78010bfee95909d605663d',
    messagingSenderId: '566798140808',
    projectId: 'vaulted-f1ef6',
    storageBucket: 'vaulted-f1ef6.firebasestorage.app',
    iosBundleId: 'com.example.vaulted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZy64V38COUJj537xS-yiof-zv-R_27VQ',
    appId: '1:566798140808:ios:78010bfee95909d605663d',
    messagingSenderId: '566798140808',
    projectId: 'vaulted-f1ef6',
    storageBucket: 'vaulted-f1ef6.firebasestorage.app',
    iosBundleId: 'com.example.vaulted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSRKDy4mAekmREUGlfZwEBAXqh23BQyY',
    appId: '1:566798140808:web:9b3577d382b1922305663d',
    messagingSenderId: '566798140808',
    projectId: 'vaulted-f1ef6',
    authDomain: 'vaulted-f1ef6.firebaseapp.com',
    storageBucket: 'vaulted-f1ef6.firebasestorage.app',
    measurementId: 'G-Z0CHMLDB3Q',
  );
}
